{{- if and .Values.paperless.secretKeyRef.create (not .Values.paperless.secretKeyRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.fullname" . }}-secret
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{randAlphaNum 32 | b64enc | quote }}
{{- end }}