{{- if and .Values.wallabag.symfonySecret.create (not .Values.wallabag.symfonySecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  # use existing Secret if possible
  {{- $secretName := include "wallabag.fullname" . }}
  {{- $secretByte := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if and $secretByte (hasKey $secretByte.data .Values.wallabag.symfonySecret.secretKey) }}
  {{ .Values.wallabag.symfonySecret.secretKey }}: {{ index $secretByte.data .Values.wallabag.symfonySecret.secretKey }}
  {{- else }}
  {{ .Values.wallabag.symfonySecret.secretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}